name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: fwal/setup-swift@v1
      with:
        swift-version: "5.6.0"
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
      
  docs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: fwal/setup-swift@v1
      with:
        swift-version: "5.6.0"
    - uses: fwcd/swift-docc-action@v1
      with:
        target: RxConcurrency
        output: ./docs
        hosting-base-path: RxConcurrency
        disable-indexing: 'true'
        transform-for-static-hosting: 'true'

